[package]
name = "rust"
version = "0.1.0"
authors = ["william.rudenmalmhogman <me@whn.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heapless = "0.7.0"
hash32 = "0.2.1"
ringbuffer = "0.7.1"
